version: "3.12"
services:
  server:
    container_name: server
    build: .
    entrypoint: /django
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-bank:
    image: redis:latest
    container_name: redis-bank
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - server
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  static:
  media:
  postgres_data:
