# Generated by Django 5.0 on 2024-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bot token', models.CharField(max_length=255)),
                ('Bot name', models.CharField(max_length=255)),
                ('Bot username', models.CharField(max_length=255)),
            ],
        ),
    ]
