# Generated by Django 5.0 on 2024-06-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='Group ID',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
