# Generated by Django 5.0 on 2024-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_telegrambot_bot_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255, verbose_name='Lead ID')),
                ('lead_owner', models.CharField(max_length=255, verbose_name='Lead owner')),
            ],
        ),
    ]
